version: "3"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - database
    command: python app.py

  database:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asa
